# file=open("Fileprogram.txt","w")
# file.close()
# file=open("Fileprogram.txt","w")
# file.write("iam farsan")
# file.close()
# file=open("Fileprogram.txt","r")
# content=file.read()
# print(content)
# file.close()
file=open("Fileprogram.txt","a")
file.write(" ,iam a student")
file.close()
